### PR TITLE
Automate toil around management of ACL rules

### PR DESCRIPTION
**Pull request by anishasthana**
Sample command: python scripts/trino_acl.py -a delete --type tables --name cost-management --resource-name costmgmt

As a note, you _will_ need Python3.10 on your system. I'm aiming to containerize this soon as well to simplify running things

Signed-off-by: Anish Asthana <anishasthana1@gmail.com>

### CODE REVIEW

**Comment by anishasthana** [comment]
I have created a toolbox image you can use for testing things out. Simply run the following commands
```
toolbox create --image quay.io/internaldatahub/data-hub-helpers:1
toolbox enter data-hub-helpers-1
trino_acl <args>
```
It will create a file in your local directory with the latest acl. You can just raise a PR with the generated file too.

**Review by lucferbux — APPROVED** [review]
/lgtm

**Review by lucferbux — APPROVED** [review]
/lgtm

**Pull request merged**
